[package]
name = "bevy-in-app"
version = "0.3.0"
authors = ["jinleili"]
edition = "2021"
rust-version = "1.78"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
# default = ["bevy_debug_stepping"]
bevy_debug_stepping = ["bevy/bevy_debug_stepping"]

[dependencies]
libc = "*"
raw-window-handle = "0.6"
wgpu = "0.20"
# bevy = { git = "https://github.com/bevyengine/bevy", rev = "ec1aa48fc", features = [
bevy = { version = "0.14.1", features = [
    # bevy = { path = "../bevy", features = [
    "bevy_audio",
    "bevy_sprite",
    "bevy_winit",
    "bevy_pbr",
    "bevy_text",
    "bevy_ui",
    "tonemapping_luts",
    "vorbis",
    "png",
    "bevy_debug_stepping",
], default-features = true }
bevy_tasks = { version = "0.14.1" }
uuid = { version = "1.7.0", features = ["v4"] }
log = "0.4"

[target.'cfg(target_os = "ios")'.dependencies]
core-graphics = "*"
objc = "*"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
jni = "0.21"
jni_fn = "0.1"
ndk-sys = "0.6"
ndk = "0.9.0"
ndk-context = "*"
log-panics = "*"

[profile.dev]
opt-level = 1 # 1 for minimal optimization and good debugging.
