[package]
name = "bevy-in-app"
version = "0.1.0"
authors = ["jinleili"]
edition = "2021"
rust-version = "1.64"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
libc = "*"
raw-window-handle = "0.5"
wgpu = "0.14"
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = [
    "bevy_audio",
    "bevy_asset",
    "bevy_sprite",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_text",
    "bevy_ui",
    "vorbis",
    "filesystem_watcher"
], default-features = false }
# bevy = { path = "../forks/bevy", features = [
#     "bevy_audio",
#     "bevy_asset",
#     "bevy_sprite",
#     "bevy_winit",
#     "bevy_core_pipeline",
#     "bevy_pbr",
#     "bevy_render",
#     "bevy_text",
#     "bevy_ui",
#     "vorbis",
#     "filesystem_watcher"
# ], default-features = false }

[target.'cfg(target_os = "ios")'.dependencies]
core-graphics = "*"
objc = "*"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19"
jni_fn = "0.1"
ndk-sys = "*"
ndk = "0.7"
ndk-context = "*"
log-panics = "*"
